### ISSUE TITLE
npm installs 1.2.0?

### ISSUE THREAD

**Issue by shovemedia** [developit/preact-redux#13] opened 2017-03-31 14:24 UTC
I get 1.2.0 unless I specify:
npm install preact-redux@latest
that shouldn't be necessary, right?

**Comment by developit** [comment] 2017-04-03 00:39
@shovemedia are you using a boilerplate? This doesn't seem to be an issue, or at least I can't reproduce\* and can't think of anything that would cause it. I am going to close this out because I am convinced it's unrelated, but I'm happy to help you debug. It could even be a caching issue if you're using a custom npm regsitry.

\*: <img width="500" alt="screen shot 2017-04-02 at 8 38 45 pm" src="https://cloud.githubusercontent.com/assets/105127/24592416/6abc6818-17e4-11e7-957e-1bc51636d324.png">

**Closed by developit** 2017-04-03 00:39 UTC

**Comment by shovemedia** [comment] 2017-04-03 00:43
ok to close. I *think* I somehow had a weird local install. Not using a custom registry, but agreed there must've (hopefully) been some kind of cache issue.
